In [7]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [12]:
df_train = pd.read_csv('/kaggle/BackpackPred/train.csv')
df_test = pd.read_csv('/kaggle/BackpackPred/test.csv')
df_sub = pd.read_csv('/kaggle/BackpackPred/sample_submission.csv')

In [13]:
df_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 300000 entries, 0 to 299999
Data columns (total 11 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   id                    300000 non-null  int64
 1   Brand                 290295 non-null  object
 2   Material              291653 non-null  object
 3   Size                  293405 non-null  object
 4   Compartments          300000 non-null  float64
 5   Laptop Compartment    292556 non-null  object
 6   Waterproof            292950 non-null  object
 7   Style                 292030 non-null  object
 8   Color                 290050 non-null  object
 9   Weight Capacity (kg)  299862 non-null  float64
 10  Price                 300000 non-null  float64
dtypes: float64(3), int64(1), object(7)
memory usage: 25.2+ MB

In [14]:
df_test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200000 entries, 0 to 199999
Data columns (total 10 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   id                    200000 non-null  int64
 1   Brand                 193773 non-null  object
 2   Material              194387 non-null  object
 3   Size                  195619 non-null  object
 4   Compartments          200000 non-null  float64
 5   Laptop Compartment    195038 non-null  object
 6   Waterproof            195189 non-null  object
 7   Style                 194847 non-null  object
 8   Color                 193215 non-null  object
 9   Weight Capacity (kg)  199923 non-null  float64
dtypes: float64(2), int64(1), object(7)
memory usage: 15.3+ MB

In [24]:
df_test.isna().sum()[df_test.isna().sum() != 0]

Material                5613
Size                    4381
Laptop Compartment      4962
Waterproof              4811
Style                   5153
Color                   6785
Weight Capacity (kg)      77
dtype: int64

In [50]:
df_train.isna().sum()[df_train.isna().sum() != 0]

Waterproof              7050
Style                   7970
Color                   9950
Weight Capacity (kg)     138
dtype: int64

In [32]:
df_train['Brand'].value_counts()

Brand
Under Armour    69697
Adidas          60077
Nike            57336
Puma            56814
Jansport        56076
Name: count, dtype: int64

In [21]:
list(df_train['Brand'].dropna().unique())

['Jansport', 'Under Armour', 'Nike', 'Adidas', 'Puma']

In [22]:
df_train['Brand'] = df_train['Brand'].fillna(np.random.choice(list(df_train['Brand'].dropna().unique())))
df_test['Brand'] = df_test['Brand'].fillna(np.random.choice(list(df_test['Brand'].dropna().unique())))

In [26]:
df_train['Material'].value_counts()

Material
Polyester    79630
Leather      73416
Nylon        70603
Canvas       68004
Name: count, dtype: int64

In [35]:
df_test['Material'].value_counts()

Material
Polyester    54136
Leather      50759
Nylon        48593
Canvas       46512
Name: count, dtype: int64

In [27]:
list(df_train['Material'].dropna().unique())

['Leather', 'Canvas', 'Nylon', 'Polyester']

In [34]:
df_train.loc[df_train['Material'].isna(), 'Material'] = np.random.choice(list(df_train['Material'].dropna().unique()), size=df_train['Material'].isna().sum(), p=[0.3, 0.3, 0.2, 0.2])
df_test.loc[df_test['Material'].isna(), 'Material'] = np.random.choice(list(df_train['Material'].dropna().unique()), size=df_test['Material'].isna().sum(), p=[0.3, 0.3, 0.2, 0.2])

'Missing in Train:'

Size                    6595
Laptop Compartment      7444
Waterproof              7050
Style                   7970
Color                   9950
Weight Capacity (kg)     138
dtype: int64

'Missing in Test:'

Size                    4381
Laptop Compartment      4962
Waterproof              4811
Style                   5153
Color                   6785
Weight Capacity (kg)      77
dtype: int64

In [40]:
df_train['Size'].value_counts()

Size
Medium    101906
Large      98643
Small      92856
Name: count, dtype: int64

In [41]:
df_test['Size'].value_counts()

Size
Medium    67775
Large     65684
Small     62160
Name: count, dtype: int64

In [43]:
df_train.loc[df_train['Size'].isna(), 'Size'] = np.random.choice(list(df_train['Size'].dropna().unique()), size=df_train['Size'].isna().sum(), p = [0.4, 0.3, 0.3])
df_test.loc[df_test['Size'].isna(), 'Size'] = np.random.choice(list(df_test['Size'].dropna().unique()), size=df_test['Size'].isna().sum(), p = [0.4, 0.3, 0.3])

In [45]:
df_train['Laptop Compartment'].value_counts()

Laptop Compartment
Yes    148342
No     144214
Name: count, dtype: int64

In [49]:
df_test['Laptop Compartment'].value_counts()

Laptop Compartment
Yes    100664
No      99336
Name: count, dtype: int64

In [48]:
df_train.loc[df_train['Laptop Compartment'].isna(), 'Laptop Compartment'] = np.random.choice(list(df_train['Laptop Compartment'].dropna().unique()), size=df_train['Laptop Compartment'].isna().sum(), p = [0.6, 0.4])
df_test.loc[df_test['Laptop Compartment'].isna(), 'Laptop Compartment'] = np.random.choice(list(df_test['Laptop Compartment'].dropna().unique()), size=df_test['Laptop Compartment'].isna().sum(), p = [0.6, 0.4])

In [53]:
df_train['Waterproof'].value_counts()

Waterproof
Yes    148077
No     144873
Name: count, dtype: int64

In [58]:
df_test['Waterproof'].value_counts()

Waterproof
Yes    101035
No      98965
Name: count, dtype: int64

In [57]:
df_train.loc[df_train['Waterproof'].isna(), 'Waterproof'] = np.random.choice(list(df_train['Waterproof'].dropna().unique()), size = df_train['Waterproof'].isna().sum())
df_test.loc[df_test['Waterproof'].isna(), 'Waterproof'] = np.random.choice(list(df_test['Waterproof'].dropna().unique()), size = df_test['Waterproof'].isna().sum())

In [80]:
df_train.isna().sum()[df_train.isna().sum() != 0]

Series([], dtype: int64)

In [60]:
df_train['Style'].value_counts()

Style
Messenger    100031
Tote          97438
Backpack      94561
Name: count, dtype: int64

In [61]:
df_test['Style'].value_counts()

Style
Messenger    66387
Tote         65089
Backpack     63371
Name: count, dtype: int64

In [64]:
df_train.loc[df_train['Style'].isna(), 'Style'] = np.random.choice(list(df_train['Style'].dropna().unique()), size=df_train['Style'].isna().sum())
df_test.loc[df_test['Style'].isna(), 'Style'] = np.random.choice(list(df_test['Style'].dropna().unique()), size=df_test['Style'].isna().sum())

In [66]:
df_train['Color'].value_counts()

Color
Pink     51690
Gray     50280
Blue     48097
Red      47219
Green    46386
Black    46378
Name: count, dtype: int64

In [70]:
df_test['Color'].value_counts()

Color
Pink     35475
Gray     33909
Blue     33351
Green    32874
Black    32332
Red      32059
Name: count, dtype: int64

In [69]:
df_train.loc[df_train['Color'].isna(), 'Color'] = np.random.choice(list(df_train['Color'].dropna().unique()), size = df_train['Color'].isna().sum(), p = [0.3, 0.2, 0.2, 0.1, 0.1, 0.1])
df_test.loc[df_test['Color'].isna(), 'Color'] = np.random.choice(list(df_test['Color'].dropna().unique()), size = df_test['Color'].isna().sum(), p = [0.3, 0.2, 0.2, 0.1, 0.1, 0.1])

In [73]:
df_train['Weight Capacity (kg)'].value_counts()

Weight Capacity (kg)
5.000000     4286
30.000000     185
11.898250     123
22.898382     116
14.908437     101
             ...
29.697814       1
17.917185       1
21.844401       1
24.234022       1
21.829597       1
Name: count, Length: 181596, dtype: int64

In [74]:
df_test['Weight Capacity (kg)'].value_counts()

Weight Capacity (kg)
5.000000     2982
30.000000     129
11.898250      93
14.908437      83
22.898382      77
             ...
22.959198       1
24.415831       1
6.812546        1
25.053977       1
14.137846       1
Name: count, Length: 128897, dtype: int64

In [79]:
df_train['Weight Capacity (kg)'] = df_train['Weight Capacity (kg)'].fillna(5.0)
df_test['Weight Capacity (kg)'] = df_test['Weight Capacity (kg)'].fillna(5.0)

In [85]:
from sklearn.preprocessing import LabelEncoder

In [103]:
df_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 300000 entries, 0 to 299999
Data columns (total 10 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   Brand                 300000 non-null  int64
 1   Material              300000 non-null  int64
 2   Size                  300000 non-null  int64
 3   Compartments          300000 non-null  float64
 4   Laptop Compartment    300000 non-null  int64
 5   Waterproof            300000 non-null  int64
 6   Style                 300000 non-null  int64
 7   Color                 300000 non-null  object
 8   Weight Capacity (kg)  300000 non-null  float64
 9   Price                 300000 non-null  float64
dtypes: float64(3), int64(6), object(1)
memory usage: 22.9+ MB

In [104]:
df_test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200000 entries, 0 to 199999
Data columns (total 9 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   Brand                 200000 non-null  int64
 1   Material              200000 non-null  int64
 2   Size                  200000 non-null  int64
 3   Compartments          200000 non-null  float64
 4   Laptop Compartment    200000 non-null  int64
 5   Waterproof            200000 non-null  int64
 6   Style                 200000 non-null  int64
 7   Color                 200000 non-null  object
 8   Weight Capacity (kg)  200000 non-null  float64
dtypes: float64(2), int64(6), object(1)
memory usage: 13.7+ MB

In [88]:
df_train = df_train.drop('id', axis = 1)
df_test = df_test.drop('id', axis = 1)

In [94]:
label = LabelEncoder()

In [95]:
df_train['Brand'] = label.fit_transform(df_train['Brand'])
df_test['Brand'] = label.transform(df_test['Brand'])

In [98]:
df_train['Material'] = label.fit_transform(df_train['Material'])
df_test['Material'] = label.transform(df_test['Material'])

In [99]:
df_train['Size'] = label.fit_transform(df_train['Size'])
df_test['Size'] = label.transform(df_test['Size'])

In [100]:
df_train['Laptop Compartment'] = label.fit_transform(df_train['Laptop Compartment'])
df_test['Laptop Compartment'] = label.transform(df_test['Laptop Compartment'])

In [101]:
df_train['Waterproof'] = label.fit_transform(df_train['Waterproof'])
df_test['Waterproof'] = label.transform(df_test['Waterproof'])

In [102]:
df_train['Style'] = label.fit_transform(df_train['Style'])
df_test['Style'] = label.transform(df_test['Style'])

In [105]:
df_train['Color'] = label.fit_transform(df_train['Color'])
df_test['Color'] = label.transform(df_test['Color'])

In [106]:
from sklearn.linear_model import LinearRegression

In [107]:
X_train = df_train.drop('Price', axis = 1)
y_train = df_train['Price']
X_test = df_test.copy()

In [108]:
model = LinearRegression()

In [109]:
model.fit(X_train, y_train)

LinearRegression()

In [110]:
y_pred = model.predict(X_test)

In [111]:
df_sub['Price'] = y_pred

In [112]:
df_sub.to_csv('sub.csv', index = False, index_label = False)